CREATE TABLE PARKING_SLOTS (
    DetectedTime Timestamp NOT NULL,
    Slot1 BOOLEAN NOT NULL,
    Slot2 BOOLEAN NOT NULL,
    Slot3 BOOLEAN NOT NULL,
    Slot4 BOOLEAN NOT NULL,
    Slot5 BOOLEAN NOT NULL,
    Slot6 BOOLEAN NOT NULL,
    Slot7 BOOLEAN NOT NULL,
    Slot8 BOOLEAN NOT NULL,
    Slot9 BOOLEAN NOT NULL,
    Slot10 BOOLEAN NOT NULL,
    Slot11 BOOLEAN NOT NULL
);

SELECT * FROM PARKING_SLOTS;

